import type {NextPage} from 'next'
import Head from 'next/head'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import {motion} from "framer-motion";
import InfoSection, {InfoSectionTypes} from "../components/infoSection";

const Home: NextPage = () => {

  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <Header sectionContainerId={'main'}/>

      {/*  Make this a div of type section header or something with a max height so IT can scroll when we click on stuff */}
      <main id={'main'} className={styles.main}>

        <InfoSection infoSectionType={InfoSectionTypes.Home} anchorId={'home'}/>
        <InfoSection infoSectionType={InfoSectionTypes.AboutMe} anchorId={'about-me'}/>
        <InfoSection infoSectionType={InfoSectionTypes.Skills} anchorId={'skills'}/>
        <InfoSection infoSectionType={InfoSectionTypes.Experience} anchorId={'experience'}/>
        <InfoSection infoSectionType={InfoSectionTypes.Education} anchorId={'education'}/>
        <InfoSection infoSectionType={InfoSectionTypes.SideProjects} anchorId={'side-projects'}/>

      </main>
    </div>
  )
}

export default Home;
